cond0_instrux = ['INSTRUCTIONS:',
                 '',
                 'In this study we are interested in how people use information to make',
                 'decisions.  You will repeatedly select from one of three decks of cards,',
                 'and you will gain a certain number of points on each draw.',
                 'Some decks may be better than others.',  
                 'Click on a deck to select a card from it.',  
                 '',
                 'Each time you draw, the number of points you received',
                 'for drawing that card will be displayed.',  
                 '',
                 'Your goal is to try to gain as many points as possible.',
                 '']

cond1_instrux = ['INSTRUCTIONS:',
                 '',
                 'In this study we are interested in how people use information to make',
                 'decisions.  You will repeatedly select from one of three decks of cards,',
                 'and you will lose a certain number of points on each draw.',
                 'Some decks may be better than others.',  
                 'Click on a deck to select a card from it.',  
                 '',
                 'Each time you draw, the number of points you lost',
                 'for drawing that card will be displayed.',  
                 '',
                 'You will start with 50,000 points.',
                 'Your goal is to try to lose as few points as possible.', 
                 '']

cond2_instrux = ['INSTRUCTIONS:',
                 '',
                 'In this study we are interested in how people use information to make',
                 'decisions.  You will repeatedly select from one of three decks of cards,',
                 'and you will gain or lose a certain number of points on each draw.',
                 'Some decks may be better than others.',  
                 'Click on a deck to select a card from it.',  
                 '',
                 'Each time you draw, the number of points you received',
                 'for drawing that card will be displayed.',  
                 '',
                 'Your goal is to try to gain as many points as possible.',
                 '']

